require("juliangra.plugins-setup")
require("juliangra.core.options")
require("juliangra.core.keymaps")
require("juliangra.core.colorscheme")

-- Plugins
require("juliangra.plugins.comment")
require("juliangra.plugins.nvim-tree")
require("juliangra.plugins.lualine")
require("juliangra.plugins.telescope")
require("juliangra.plugins.nvim-cmp")
-- require("juliangra.plugins.lsp.mason")
-- require("juliangra.plugins.lsp.lspconfig")
-- require("juliangra.plugins.lsp.null-ls")
require("juliangra.plugins.autopairs")
require("juliangra.plugins.treesitter")
require("juliangra.plugins.gitsigns")
require("juliangra.plugins.bufferline")
require("juliangra.plugins.minimap")
